### ISSUE TITLE
Saving to a GFile provided by GtkFileChooserNative fails under certain conditions

### ISSUE THREAD

**Issue by junrrein** [flatpak/xdg-desktop-portal-gtk#131]
Using Flatpak 0.11.7 under Fedora 28.

This is an issue I run into when packaging my Gtkmm app[1] for Flathub. I provide a "minimal" test case for this bug[2] but it's also in C++, since it's what I know.

The test case does the following: It generates text data (around 1.7 MB) and tries to save it to a destination choosed by the user via a `GtkFileChooserNative` dialog.

To save the data, three methods are used: `g_file_replace_contents`, `g_file_copy`, and `g_file_move`. The results are identical, but they are included to be sure.

I can always replicate the issue doing the following with my test app:

1. Open the application.
2. Save the file. Note down the filename and path used. Saving should succeed with the following output:

```
Target filepath: /run/user/1000/doc/8e667a75/text file.txt
Saving using g_file_replace_contents
Success
Saving using g_file_copy
Success
Saving using g_file_move
Success
```

3. Close the application.
4. Delete the generated file.
5. Reopen the application.
6. Save the file using **the same** filename and path used previously. Saving fails with the following output:

```
Target filepath: /run/user/1000/doc/8e667a75/text file.txt
Saving using g_file_replace_contents
Error opening file “/run/user/1000/doc/8e667a75/text file.txt”: No such file or directory
Saving using g_file_copy
Error opening file “/run/user/1000/doc/8e667a75/text file.txt”: No such file or directory
Saving using g_file_move
Error opening file “/run/user/1000/doc/8e667a75/text file.txt”: No such file or directory
```

The error keeps happening until I log out and log in again.

[1] https://github.com/junrrein/pdfslicer
[2] https://github.com/junrrein/flatpak-saving-file

**Comment by nedrichards** [comment]
I can reproduce this.

**Comment by matthiasclasen** [comment]
I believe this was a bug in the document portal fuse implementation that has since been fixed.

**Comment by nedrichards** [comment]
Great! Do you know which version it was fixed in? @junrrein was holding his app on Flathub until it was sorted so I'd love to be able to unblock that.

**Comment by matthiasclasen** [comment]
Alex' document portal fomix is in 1.0.3

**Comment by junrrein** [comment]
I can confirm the issue is fixed. Thanks!
