### ISSUE TITLE
offers to install missing app from Software, but doesn't show the app once installed

### ISSUE THREAD

**Issue by andreasn** [flatpak/xdg-desktop-portal-gtk#144]
I wanted to open a txt-file that was sent to me on Telegram. I was missing any app that could read txt-files, so the portal offered me to look for it in GNOME Software. I then installed gEdit from that, but when I returned to the portal, it still didn't show the Text Editor. I had to hunt it down under the round button with the 3 dots.

**Comment by matthiasclasen** [comment]
Did you return to the portal by opening it again from telegram, or did you just keep the dialog open ?

**Comment by andreasn** [comment]
I kept it open.

**Comment by andreasn** [comment]
Closing it, and then opening it again would break the flow.
Not sure how to best solve it though. Should the portal dialog constantly scan for new apps?

**Comment by matthiasclasen** [comment]
the implementation problem here is that the dialog is not doing any scanning at all - it just gets handed a list of apps to show, from the portal frontend. We need some new mechanism to update the list
