### ISSUE TITLE
Respect lockdown settings

### ISSUE THREAD

**Issue by hadess** [flatpak/xdg-desktop-portal-gtk#155]
In `gsettings-desktop-schemas`' `org.gnome.desktop.lockdown` schema, there are keys to:
- disabling saving to disk (`disable-save-to-disk`)
- disabling printing (`disable-printing`)
- disabling URL and mime-handlers (`disable-application-handlers`)

In those 3 cases, the portals should return errors (without showing a UI?) if the setting is locked down.

**Comment by matthiasclasen** [comment]
See https://github.com/flatpak/xdg-desktop-portal-gtk/pull/156 and https://github.com/flatpak/xdg-desktop-portal/pull/258
