### ISSUE TITLE
Improve icon handling in notifications

### ISSUE THREAD

**Issue by TingPing** [flatpak/xdg-desktop-portal-gtk#159]
So there are two surfaces I think it would be a good ideal to reduce if possible here:

Firstly icons can be passed as bytes in which case we directly call `gdk_pixbuf_new_from_stream()` on them. This results in exposing every single pixbuf loader we have to untrusted data. The ideal solution to this is to move it out of process in its own sandbox.

Secondly icons can be passed as a path (which also isn't correctly mapped to sandbox paths) in which case we directly pass it on to the actual notification daemon where we can safely assume they do not treat it as untrusted data and directly expose it to all loaders.

This is of course harder to fix but we can take some preventative steps like white-listing more "safe" codecs like png and svg. We should also look into making `gnome-shell` move its decoding out of process. We could also take a more drastic approach of converting all paths to bytes which we safely decode. That might hurt performance and probably not all daemons support this.

**Comment by matthiasclasen** [comment]
I would suggest that we sanitize icons in the portal frontend, and only let safe stuff through. We could e.g. convert everything to png

**Comment by matthiasclasen** [comment]
There is some validation in the frontend alreday, actually.

**Comment by matthiasclasen** [comment]
I think we just need to forbid file icons. Maybe we can make the notification backend load those and send them as pngs ?

**Comment by TingPing** [comment]
> There is some validation in the frontend alreday, actually.

Just that its a GIcon.

> I think we just need to forbid file icons. Maybe we can make the notification backend load those and send them as pngs ?

I do think that is the right place to do it. I do question making everything a PNG though since SVGs will lose correct scaling since only the end daemon knows the output size.

**Comment by TingPing** [comment]
Also looks like `xdg-desktop-portal-kde` only accepts string icons anyway so passing by bytes was always broken there.

**Comment by matthiasclasen** [comment]
https://github.com/flatpak/xdg-desktop-portal/pull/262
