### ISSUE TITLE
Add support for Sylpheed

### ISSUE THREAD

**Issue by hadess** [flatpak/xdg-desktop-portal-gtk#189]
As done in nautilus-sendto:
https://gitlab.gnome.org/GNOME/nautilus-sendto/blob/master/src/nautilus-sendto.c#L341

**Comment by matthiasclasen** [comment]
we're just using mailto uris now

**Comment by hadess** [comment]
> we're just using mailto uris now

mailto URIs aren't standard, and differ between mail clients.

**Comment by matthiasclasen** [comment]
I've tested it with the two clients we had explicit code for before, evolution and thunderbird, and they both work fine with the mailto uris we create.

**Comment by matthiasclasen** [comment]
One reason why I'm interested in simplifying this is that I want to move this to the frontend, and make it basically reuse the open-uri portal code, so we can
- present an app chooser for mail clients
- export files to attach to make attachments work with sandboxed mail clients
- share code with the openuri portal

**Comment by hadess** [comment]
I understand. That might be a good time to document exactly the format of the URI, to turn it into a defacto standard ("want your mail client to work with this, this is the format it needs to support").

**Comment by hadess** [comment]
See https://github.com/flatpak/xdg-desktop-portal/pull/418
