### ISSUE TITLE
Usability problems with opening sandboxed app's files in other applications

### ISSUE THREAD

**Issue by maymage** [flatpak/xdg-desktop-portal-gtk#193]
Hi, 
I was encourage to refer a bug report 
https://gitlab.gnome.org/GNOME/geary/issues/335
over to here. In short

**About you**
 * Installed latest Geary=email client
 * Version: 3.32 stable x86_64 flathub
 * Installation method: flathub via flatpak
 * Your desktop: Gnome 3.32
 * Your operating system and version: Ubuntu 19.04 prerelease
 * Email provider: Gmail

**Current status**

Receiving via Geary an email with multiple images in jpg format attached and clicking on one of these 

0) Geary asks, with which application to open, i.e. view the clicked image, 
   instead of using the default image viewer application chosen via system settings. 

Selecting Eyes of Gnome for instance for the first image, it is shown correctly via Eyes of Gnome. But
 
1) Geary doesn't let me choose Eyes of Gnome as a default for opening pictures.

2) Within Eyes of Gnome one cannot move forward to view the second picture.

3) Closing Eyes of Gnome and clicking the second picture, Geary asks again for an application to open with. 

**Analysis**

I was told, that  2 is Geary's fault, whereas 0,1,3 is Flatpak's standard behaviour. In any case the current implementation re default applications constitutes a draw back with respect to the standard, non flatpak installation. 

**What is the expected correct behaviour?**

1) Geary should use the system default applications for opening attachments via left click.

2) Geary should let choose default applications to open attachments via right click.

3) Multiple files of the same type in the attachment of one Email should be browsable by the application, which opens those parts of the attachment.  

**Feature request for xdg**

1) Make the system's default applications the default applications for sandboxed apps, i.e. 
opening images in a sandboxed, non image related application, should refer to the systems's default image handling application; opening a pdf in a sandboxed, non pdf related application, should refer to the systems default pdf=document viewer application, and so on. 

2) Make a per sandboxed app selection of default apps available upon right click. 

**Caveat**

For instance, if the systems default document app is Libre-office, this could imply, that also pdf's as email attachments are opened by Libre-office, which might be a security concern in general.
A way this concern could be adressed is to warn the user in case a default app is not sandboxed itself and ask him to choose, as under "Feature requests for xdg, point 2" above, an default application. This would not be 100% safe yet, however wouldn't be a draw back to the current situation neither. 

_____________________________________________________

May I kindly ask to report back to 
https://gitlab.gnome.org/GNOME/geary/issues/335
if and when a solution is cooked up?

**Comment by matthiasclasen** [comment]
We added SaveFiles support in the next portal version which lets an app request a save location for multiple files in a single call.
