### ISSUE TITLE
Separate GTK and GNOME

### ISSUE THREAD

**Issue by AdrianVovk** [flatpak/xdg-desktop-portal-gtk#201]
I'm currently developing my own GTK-based DE With a completely different compositor than mutter (wlroots based).

The issue is, this project isn't just the portal for GTK, it's the portal for GNOME. It would be great to separate the gnome-shell specific functions, like the screenshooter, and the generic GTK functions.

How should I proceed? I see no sense in rewriting the generic GTK functionality in my own portals impl, since this project exists. I cannot easily port all of mutter into my compositor either.

Thank you

**Comment by matthiasclasen** [comment]
xdg-desktop-portal has mechanisms to replace individual portal backends, depending upon the environment.

If your compositor offers similar-enough apis for equivalent functionality, adding support for that to the existing backends is certainly possible too - we do that e.g. in the notification backend, which can talk org.gtk.Notifications or org.freedesktop.Notifications

**Comment by AdrianVovk** [comment]
Is there some priority system, or should my distro replace gtk.portal and change `Interfaces` and `UseIn`?

**Comment by matthiasclasen** [comment]
UseIn is the amount of priorization we have right now - xdg-desktop-portal first tries to match that to the running desktop, then uses the first available

**Comment by AdrianVovk** [comment]
@matthiasclasen So if my `XDG_CURRENT_DESKTOP=carbon` then I would implement the interfaces I want to override and set `UseIn=carbon`, and then the rest will go to xdg-desktop-portal-gtk even though `UseIn=gnome` there. Correct?

**Comment by matthiasclasen** [comment]
sorry for not noticing the question until now. But yes, that is how it should work

**Comment by AdrianVovk** [comment]
@matthiasclasen Great, thank you!

**Comment by jokeyrhyme** [comment]
Hmmm, looks like this has happened? https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome
