### ISSUE TITLE
Add Russian translation

### ISSUE THREAD

**Issue by webmastak** [flatpak/xdg-desktop-portal-gtk#205]
Please add [Russian](https://github.com/flatpak/xdg-desktop-portal-gtk/pull/206) translation.

**Comment by AsciiWolf** [comment]
Already done, but please fix the issues I mentioned [here](https://github.com/flatpak/xdg-desktop-portal-gtk/commit/ae6d18546305e913999ea56681c33a9628be502b) and consider making translation for [xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal) as well.

**Comment by AsciiWolf** [comment]
@webmastak Any news about the Russian file update? I see that you closed the [PR](https://github.com/flatpak/xdg-desktop-portal-gtk/pull/209).

**Comment by AsciiWolf** [comment]
The file needs to get fixed or the translation needs to be removed before next xdg-desktop-portal-gtk release.

Adding Matthias Clasen to CC.

/cc @matthiasclasen

**Comment by webmastak** [comment]
There is no conflict! [Pull reguest](https://github.com/flatpak/xdg-desktop-portal-gtk/pull/212)
