### ISSUE TITLE
Endless spam of GDBus.Error:org.freedesktop.portal.Error.Failed: messages in syslog

### ISSUE THREAD

**Issue by Erick555** [flatpak/xdg-desktop-portal-gtk#215]
Hello, I have endless spam from `user@xxx.service` in syslog:
`Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list: Cannot invoke method; proxy is for the well-known name org.gnome.Shell without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag`

Distro: Arch Linux
DE: KDE Plasma 5.16.3
xdg-desktop-portal-gtk: 1.4.0
xdg-desktop-portal: 1.4.2
xdg-desktop-portal-kde: 5.16.3

**Comment by hadess** [comment]
The gtk portal shouldn't be running under KDE. Would it be because the KDE backend doesn't implement that portal? Which application are you running when this happens?

CC @grulja

**Comment by hadess** [comment]
https://github.com/flatpak/xdg-desktop-portal-gtk/blob/master/src/background.c#L44

**Comment by Erick555** [comment]
I have all `xdg-portal`, `xdg-portal-kde`, `xdg-portal-gtk` running. They are started automatically from `systemd-user` instance after I log into DE.

**Comment by Erick555** [comment]
Hm, after updating recent system updates with KDE Frameworks 5.60.0 being most significant and rebooting, the issue doesn't happen anymore. `xdg-portal-gtk` also isn't running. I'll re-open if I see it again

**Comment by matthiasclasen** [comment]
We should still not spam, even if we can't find the gnome-shell api

**Comment by Erick555** [comment]
It seems the issue still happens  - something triggers `xdg-portal-gtk` startup which starts spamming. I can't say for now what's the cause.

**Comment by Erick555** [comment]
The application which triggers `xdg-portal-gtk` startup and subsequent spam is [spice-gtk](https://www.spice-space.org/download.html).

**Comment by Erick555** [comment]
However the spam seems comming from xdg-desktop-portal (not -gtk):

```
● xdg-desktop-portal.service - Portal service
   Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal.service; static; vendor preset: enabled)
 Main PID: 26770 (xdg-desktop-por)
   CGroup: /user.slice/user-1000.slice/user@1000.service/xdg-desktop-portal.service
           └─26770 /usr/lib/xdg-desktop-portal

Jul 16 14:43:51 localhost systemd[1510]: Starting Portal service...
Jul 16 14:43:52 localhost xdg-desktop-por[26770]: Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list: Cannot invoke method; proxy is for the well-known name org.gnome.Shell without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
Jul 16 14:43:52 localhost systemd[1510]: Started Portal service.
Jul 16 14:44:52 localhost xdg-desktop-por[26770]: Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list: Cannot invoke method; proxy is for the well-known name org.gnome.Shell without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
Jul 16 14:45:52 localhost xdg-desktop-por[26770]: Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list: Cannot invoke method; proxy is for the well-known name org.gnome.Shell without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
Jul 16 14:46:52 localhost xdg-desktop-por[26770]: Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list: Cannot invoke method; proxy is for the well-known name org.gnome.Shell without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
```

**Comment by Erick555** [comment]
The workaround is to simply remove xdg-desktop-portal-gtk from the system

**Comment by chron-isch** [comment]
Running Arch with Sway(Wayland i3 clone) here, and I'm having the same problem.

@Erick555 That is only a workaround if you're using KDE, xdg-desktop-portal depends on xdg-desktop-portal-kde or xdg-desktop-portal-gtk.

```
xdg-desktop-por[1975]: Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list: Cannot invoke method; proxy is for the well-known name org.gnome.Shell without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag
````
If I mask xdg-desktop-portal-gtk.service I get this:
```
xdg-desktop-por[1975]: Failed to get application states: GDBus.Error:org.freedesktop.systemd1.UnitMasked: Unit xdg-desktop-portal-gtk.service is masked.
```
So I traded one error message for another...

**Comment by asegarra** [comment]
I'm getting a similar error on Fedora 30 Gnome when I run flatpaks, should I open a new issue?

`xdg-desktop-por[7300]: Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: App introspection not allowed`

**Comment by Erick555** [comment]
> GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: App introspection not allowed

That sounds like something else.

**Comment by JustEvgeniy** [comment]
Running arch with swaywm. I have the same problem.

I cannot remove xdg-desktop-portal-gtk from the system because it is required as a dependency for flatpak. I could replace it with xdg-desktop-portal-kde, but this requires a lot of kde-related dependencies that I don't want to install.

xdg-desktop-portal: 1.4.2
xdg-desktop-portal-gtk: 1.4.0

**Comment by ricardoeliasg** [comment]
> I'm getting a similar error on Fedora 30 Gnome should I open a new issue?
> 
> `xdg-desktop-por[7300]: Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: App introspection not allowed`

I have exactly the same problem from asegarra with fedora 30 Gnome too. the system freeze when i open firefox or Telegram

**Comment by erlisdhima** [comment]
I was getting a similar issue:
`
xdg-desktop-por[3497]: Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: App introspection not allowed
`  


I was able to get past the issue following these steps:
1. Used [dbus-monitor](https://linux.die.net/man/1/dbus-monitor), to see what was happening in more details (as it is a dbus error).  

I saw the following output:
```
method call time=1572026972.944390 sender=:1.21 -> destination=:1.24 serial=154 path=/org/freedesktop/portal/desktop; interface=org.freedesktop.impl.portal.Background; member=GetAppState
method call time=1572026972.945211 sender=:1.24 -> destination=:1.43 serial=165 path=/org/gnome/Shell/Introspect; interface=org.gnome.Shell.Introspect; member=GetWindows
error time=1572026972.946995 sender=:1.43 -> destination=:1.24 error_name=org.freedesktop.DBus.Error.AccessDenied reply_serial=165
   string "App introspection not allowed"
error time=1572026972.947982 sender=:1.24 -> destination=:1.21 error_name=org.freedesktop.portal.Error.Failed reply_serial=154
   string "Could not get window list: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: App introspection not allowed"
signal time=1572026973.432373 sender=:1.91 -> destination=(null destination) serial=2094 path=/org/ayatana/NotificationItem/psensor/Menu; interface=com.canonical.dbusmenu; member=ItemsPropertiesUpdated
```

We see the following `path=/org/gnome/Shell/Introspect; interface=org.gnome.Shell.Introspect; member=GetWindows`

2. Using a tool like dconf Editor (on Ubuntu)
I changed `/org/gnome/shell/introspect` to true.

**What is happening:**
Apparently there's a `GetWindows` method in the introspect api which is being called by some app. 
I'm not sure what app is using that api and calling that method, but the only info I found about the api was in this merge request https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/326
Finding which app is using it will take a lot more time to find out.
The other thing I was worried when enabling this API is security, but the code changes are merged, so am assuming its OK to do the change.

**Comment by tvld** [comment]
Same issue, _exact every two minutes_:
```
Nov  1 11:02:11 tom-XPS-15-9560 xdg-desktop-por[2369]: Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: App introspection not allowed
```

**Comment by Erick555** [comment]
@tvld the fix is in xdg-desktop-portal 1.5.x while ubuntu 19.10 has 1.4.2

**Comment by tvld** [comment]
ah, clear, thanks ))...

**Comment by adatum** [comment]
On Fedora 30 and 31 (MATE desktop environment) I see the same messages in the system log:

> xdg-desktop-por[3995]: Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list: Cannot invoke method; proxy is for the well-known name org.gnome.Shell without an owner, and proxy was constructed with the G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START flag

The installed version of xdg-desktop-portal is 1.4.2. I hope this issue is resolved when the upcoming v.1.5 release makes its way into the repos.

**Comment by kenvandine** [comment]
I'd like to back port this to the 1.4 series but there I couldn't find a stable branch.  How are the stable branches maintained?

**Comment by rodalpho** [comment]
I fixed via the CLI by running

`gsettings set org.gnome.shell introspect true`

**Comment by matthiasclasen** [comment]
> I'd like to backport this to the 1.4 series but there I couldn't find a stable branch. How are the stable branches maintained?

There is no stable branch yet. If you want to start one, just base it on the 1.4.0 tag.

**Comment by adatum** [comment]
> I fixed via the CLI by running
> 
> `gsettings set org.gnome.shell introspect true`

Is that a workaround specific to Gnome Shell?

```
$ gsettings get org.gnome.shell introspect
No such schema “org.gnome.shell”
```

**Comment by rodalpho** [comment]
Yes, the "org.gnome.shell" bit rather gives it away. I'm sure there's some way to disable introspection on KDE or whatever you're using too.

**Comment by adatum** [comment]
I'm using MATE. 

What is introspection, and what are the consequences of disabling it? Also your code suggest enabling it, no?

**Comment by rodalpho** [comment]
Beats the heck out of me, I just wanted the errors to stop spamming syslog every minute. Yes I allowed it, whatever it is.

**Comment by matthiasclasen** [comment]
The background portal backend only knows how to get the information it needs from gnome-shell.

A patch to just make it quietly return nothing if the shell isn't running would be appreciated.

**Comment by theHilikus** [comment]
@kenvandine any luck with the port? i'm hoping to have a fix without having to wait 4 months for Ubuntu 20.04

**Comment by kenvandine** [comment]
I uploaded an SRU to 19.10 this morning.  It'll probably take a few weeks for the SRU team to review and accept it.

**Comment by pmarreck** [comment]
Noticed this in my logs on a relatively new 19.10 stock install while troubleshooting something else, @rodalpho 's solution worked (although may be a slight security hole, potentially?)

In related news (?), the new zfs-on-boot support has already saved my data from corruption (I had a bad USB-A-3.1-to-USB-C drive cable while using an external NVMe enclosure) and I've only had this install for 1 day lol. `zpool status` showed SUSPENDED due to I/O failures detected. Just prior to this I had a Manjaro Linux BTRFS install on the exact same hardware setup (with bad cable) which got completely hosed over time because BTRFS did not detect the issue until it was too late (started noticing odd issues and hangs a few days in; ran btrfsck which reported errors; rebooted to my manjaro USB key and a repair attempt failed; had to wipe drive and start over).

**Comment by liubomirwm** [comment]
Also experience this issue on Ubuntu 19.10.

**Comment by D10666** [comment]
Also having a similar problem whilst installing Ubuntu 19.10 on a Kingston traveler 32gb usb pen drive, setup using Rufus.

Boots perfect but during install I chose an 8gb swap partition 4gb EFI partition and rest is root ext4 partition (is this the recommended partition setup?????) 

Then whilst it's 'copying files' I get the errors highlighted in the picture attached... Any suggestions?!

Ubuntu install error picture - https://imgur.com/gallery/bnFQonh

**Comment by OGDee93** [comment]
So... no solution, right?
