### ISSUE TITLE
Application can't be found for some URIs

### ISSUE THREAD

**Issue by andyholmes** [flatpak/xdg-desktop-portal-gtk#299]
Opening a URI such as `sftp://192.168.0.25:22` doesn't find Nautilus or presumably any other application.

Instead a *No Apps available* dialog is shown, with an option to find more apps (which it doesn't.

**Comment by felipeborges** [comment]
Shouldn't Nautilus instead have to advertise the support for this mime-type? https://gitlab.gnome.org/GNOME/nautilus/-/blob/master/data/org.gnome.Nautilus.desktop.in.in#L14

**Comment by andyholmes** [comment]
Hmm, I just tried adding this with `gio mime` and [crashed the portal](https://retrace.fedoraproject.org/faf/reports/2865163/). Sorry, I've never tried to pull one of these out of abrt before.

In any case, should I instead open a report with Nautilus? Someone on #gnome-hackers implied this wasn't feasible since sftp is supported conditionally.

It seems unfortunate that this will work unsandboxed as it goes through GIO, whereas it gets filtered through GtkAppChooser by the portal.

**Comment by andyholmes** [comment]
This seems to have been fixed (somehow), so I'm closing this.
