### ISSUE TITLE
"Unhandled parent window type" when parent window is GtkPopover

### ISSUE THREAD

**Issue by mcatanzaro** [flatpak/xdg-desktop-portal-gtk#301]
Try to open a download in Epiphany. In this case, the parent window is the downloads popover. xdg-desktop-portal-gtk prints:

```
** (xdg-desktop-portal-gtk:375644): WARNING **: 17:52:19.067: Unhandled parent window type 


** (xdg-desktop-portal-gtk:375644): WARNING **: 17:52:19.067: Failed to associate portal window with parent window 
```

I wonder, is that fixable?

**Comment by matthiasclasen** [comment]
This is GTK3, so popovers are not their own surfaces, right ? So what surface is the id you're passing actually referring to?

In GTK4, with popup surfaces, this will be more interesting.

**Comment by mcatanzaro** [comment]
It looks like this bug no longer occurs, probably because we switched to using libportal instead of manual D-Bus calls.

The old code was [here](https://gitlab.gnome.org/GNOME/epiphany/-/blob/b211d985079e7ffeae5c7d66cc7cd1034fddda53/lib/ephy-flatpak-utils.c#L205) and I don't see any surface ID being passed anywhere.
