### ISSUE TITLE
Set up weblate for localization contributions

### ISSUE THREAD

**Issue by felipeborges** [flatpak/xdg-desktop-portal-gtk#324]
https://weblate.org is a great tool to attract new translators to an existing software project. It can work with gettext based translation projects and works nicely with github. It is a FOSS tool that you pay for hosting. They offer free hosting for FOSS projects, so we could request free hosting if we decide to use the tool here. The Fedora project uses it and hosts its own instance of Weblate.

I believe it can bring many more translators than we have right now, given that currently translators need to make pull requests and there's little track of translation progress or opportunities for translation reviews.

@rffontenelle has some experience with Weblate. Could you please elaborate if there's something else to add to this proposal?

**Comment by rffontenelle** [comment]
Indeed, Weblate allows gratis hosting for free (libre) software projects. Steps are basically:
1. Register an account in Hosted Weblate (https://hosted.weblate.org) and sign in
2. Go to https://hosted.weblate.org/hosting/ for conditions and a form
3. Fill the form asking for project hosting and wait for the reply
4. Once approved, set up the flatpak-doc projects following Weblate documentation (https://docs.weblate.org/)

(btw, I'd be glad to help on this setup and maintenance, if you want me to)

**Comment by rffontenelle** [comment]
Oh, wait. This project's translation [is already set on Damned Lies](https://l10n.gnome.org/module/xdg-desktop-portal-gtk/), just like other Flatpak projects. In this case, I don't think moving it to Weblate would be wise, as it would separate from others related projects.

**Comment by felipeborges** [comment]
> Oh, wait. This project's translation [is already set on Damned Lies](https://l10n.gnome.org/module/xdg-desktop-portal-gtk/), just like other Flatpak projects. In this case, I don't think moving it to Weblate would be wise, as it would separate from others related projects.

I agree. I would have expected that damned lies would commit directly to the project instead of having translators posting pull requests.
