### ISSUE TITLE
Wayland GTK Flatpaks do not antialias fonts when run on KDE Plasma Wayland

### ISSUE THREAD

**Issue by GuiltyDoggy** [flatpak/xdg-desktop-portal-gtk#355]
Seems that 1.10.0 may have broken GTK Wayland Flatpaks when run in KDE Plasma Wayland. Fonts are blocky (not anti-aliased). See the following:

https://www.reddit.com/r/kde/comments/pzq1nc/this_week_in_kde_getting_plasma_523_ready_for/hf4ixvg/

https://discussion.fedoraproject.org/t/logout-login-bugs-in-plasma-wayland-should-i-be-using-x11/33226/7

Running on Fedora 35 Kinoite
KDE Plasma 5.22.5
xdg-desktop-portal-gtk-1.10.0-1.fc35.x86_64

**Comment by GuiltyDoggy** [comment]
Replacing with xdg-desktop-portal-gnome appears to be the solution

**Comment by pizzadude** [comment]
Installing xdg-desktop-portal-gnome and rebooting fixed it for me.

**Comment by smcv** [comment]
> I don't see any reason why the set of portals to be installed should be configurable, unless some portals have optional dependencies....

My understanding is that it's intended as a transitional mechanism, so that distros like Debian that don't have the -gnome backend yet can continue to build the GNOME-specific features into the -gtk backend.

**Comment by Erick555** [comment]
> That might be hard, though. I worry that having one backend that is used in GNOME and another used elsewhere, kept in separate repos, is going to inevitably result in bugs being fixed in one place and not the other

Maybe -gtk backend should be depreciated then everyone would gradually transit to -gnome backend  and use it the same as they used -gtk before. This would keep the status quo from user POV before -gnome was introduced.

**Comment by smcv** [comment]
> Maybe -gtk backend should be depreciated then everyone would gradually transit to -gnome backend

If that was good enough, then there would have been no point in having the -gnome backend as a separate project; the -gtk backend would have just changed its code (maybe in a branch).

As I understand it, the point of splitting them is that historically, half of the -gtk backend was equally applicable to GNOME and all other GTK-based desktops such as XFCE (and also as a portal backend of last resort for people who don't use a supported desktop environment at all but do have GTK installed), whereas the other half was specific to GNOME Shell and other purely GNOME components. The intention is that -gtk keeps the parts that are equally applicable to multiple desktops, and -gnome takes over the GNOME-specific parts.

For the Settings portal, obviously that hasn't entirely gone as intended.

**Comment by Erick555** [comment]
> The intention is that -gtk keeps the parts that are equally applicable to multiple desktops, and -gnome takes over the GNOME-specific parts. People who don't use GNOME shouldn't install the -gnome backend, and shouldn't need to install it.

Originally I thought the same but now I see that -gnome took also non-GNOME-specific parts like settings and appchooser which mean -gtk is  redundant as both gnome and non-gnome users can settle with -gnome. It's no like someone is going to pay for unused features the backend has. I agree this makes the split pointless but ship sailed. Depreciation of -gtk at least save time for maintaining two projects instead of one.

**Comment by mcatanzaro** [comment]
We just need to reenable settings and appchooser here. They'll have to coexist.

**Comment by Erick555** [comment]
Does -gtk have something that -gnome doesn't?

**Comment by Erick555** [comment]
It doesn't depend on gnome-settings-daemon since some functionality was moved to gsettings-desktop-schemas. IIRC it was even you who helped doing that so I don't understand what you are saying here.

**Comment by vchernin** [comment]
FYI Arch now has [-gtk](https://github.com/archlinux/svntogit-packages/blob/packages/xdg-desktop-portal-gtk/trunk/PKGBUILD) and [-gnome](https://github.com/archlinux/svntogit-packages/blob/packages/xdg-desktop-portal-gnome/trunk/PKGBUILD), seemingly with default build options. So it would probably be good to reenable settings and appchooser upstream.
