### ISSUE TITLE
App Chooser dialog shows "no apps available"

### ISSUE THREAD

**Issue by eternal-sorrow** [flatpak/xdg-desktop-portal-gtk#379]
`xdg-open` successfully opens the URL with an app (`.desktop` file that I created), but when I click this URL in browser, I get a xdg-dektop-portal-gtk dialogue "Open with..." that says "no apps available".

**Comment by TingPing** [comment]
What does `gio mime x-scheme-handler/https` show?

**Comment by eternal-sorrow** [comment]
Okay, fixed this with `xdg-mime default`.
