### ISSUE TITLE
Reproduce pop-up

### ISSUE THREAD

**Issue by f4rm0r** [flatpak/xdg-desktop-portal-gtk#389]
Hello everyone,
I am sorry if this has been asked before, but I have not managed to find anything on google on how to do this.

So basically I got a popup asking if an application can run in the background, I accidentally clicked on deny, and now it just crashes/gets a sigterm sent to it. The app in question is a flatpak from flathub "app.xemu.xemu". Would it be possible to activate the pop-up again or to change that specific setting somewhere on my system?

OS: Archlinux
DE: Plasma/KDE

What I have tried:
flatpak run --command=/bin/sh app.xemu.xemu

But no pop-up came from that.

**Comment by rusty-snake** [comment]
GNOME has it in its control center, for KDE I'm unsure. However the cli should work always, `flatpak permission-remove background background <APP-ID>`.

**Comment by f4rm0r** [comment]
> GNOME has it in its control center, for KDE I'm unsure. However the cli should work always, `flatpak permission-remove background background <APP-ID>`.

it worked, thank you!
