### ISSUE TITLE
1.14.1 release?

### ISSUE THREAD

**Issue by smcv** [flatpak/xdg-desktop-portal-gtk#405]
Would now be a good time for a 1.14.1 release? I think I have enough permissions in the Flatpak organization to turn the handle for the actual release if the other maintainers are busy.

All the changes since 1.14.0 seem to be the sort of thing that would be in-scope for a .1 stable release (no new features or obvious regression risks).

**Comment by TingPing** [comment]
:+1:

**Comment by smcv** [comment]
1.14.0-2 in Debian unstable is basically a preview of what a 1.14.1 would look like, so that it can get some practical testing.

**Comment by smcv** [comment]
I've prepared a release and pushed the tag, but I can't push to `main`. See #407

**Comment by smcv** [comment]
Release pushed to `main` as well.

**Comment by TingPing** [comment]
Thanks!
