### ISSUE TITLE
Typo in dynamic-launcher dialog

### ISSUE THREAD

**Issue by Beryesa** [flatpak/xdg-desktop-portal-gtk#427]
Possible typo in 
https://github.com/flatpak/xdg-desktop-portal-gtk/blob/b6a8b0a483c7b7e4148aed9de8cea30b8821b326/src/dynamic-launcher.c#L269

**Comment by sabriunal** [comment]
"C_reate" is correct, it's a mnemonic.

More information: https://www.gnome.org.tr/ceviri/ceviri-nasil-yapilir/

"Çeviri yaparken dikkat edilecek noktalar
Anımsatıcı İşareti (mnemonic)"
