### ISSUE TITLE
xdg-desktop-portal-gtk messes with my theme

### ISSUE THREAD

**Issue by Kagukara** [flatpak/xdg-desktop-portal-gtk#430]
I need a file chooser for Steam and as I use `sway`, `xdg-desktop-portal-wlr` doesn't have a file chooser so I need one that does.

When I download `xdg-desktop-portal-gtk` (AUR) my theme gets messed up. My browser and other applications think I have a light theme even though the file chooser is in dark theme. When I uninstall `xdg-desktop-portal-gtk` my theme goes back to normal.

I have tried adding `ADW_DEBUG_COLOR_SCHEME=prefer-dark` in my environment variables but it doesn't change the browser/other applications to dark theme. I have `gsettings set org.gnome.desktop.interface gtk-theme 'Marwaita Dark'`, and the theme is also set in `lxappearance`.

Please let me know what information I need to provide to help fix or how to fix this issue.

**Comment by TingPing** [comment]
You want `gsettings set org.gnome.desktop.interface color-scheme prefer-dark`
