### ISSUE TITLE
1.15/1.16 release?

### ISSUE THREAD

**Issue by smcv** [flatpak/xdg-desktop-portal-gtk#442]
It would be useful to have a new release of x-d-p-gtk on roughly the same timeline as x-d-p 1.18.x and GNOME 45, mainly for #396 and #411 (also lots of translation updates).

#438 slightly complicates that by removing functionality, although it's functionality that we hope all distributions are disabling anyway.

I think it would be good to prepare a 1.15.0 soon, and follow that shortly afterwards with a 1.16.0 if no showstopper bugs are reported. (Or it could go directly to 1.16.0, but in the past when we have skipped the "do a prerelease" stage in x-d-p the results have not always been great.)

**Comment by ebassi** [comment]
I'm happy to spin up a 1.14.2 release without #438 and then do a 1.15.0 from the current main.

**Comment by ebassi** [comment]
1.15.0 is out, though it has a build issue and will require 1.15.1.
