### ISSUE TITLE
Last update broke font rendering in GTK Flatpaks on Wayland again

### ISSUE THREAD

**Issue by Multowz** [flatpak/xdg-desktop-portal-gtk#445]
My fonts were looking fine but after I updated the package on Arch, fonts look like this. 

![image](https://github.com/flatpak/xdg-desktop-portal-gtk/assets/103082425/8fb52019-4f1b-46f9-a922-be36b8959c81)
distribution: arch linux
desktop environment: kde plasma

**Comment by smcv** [comment]
Unless you have evidence to the contrary, this is most likely to be KDE not configuring xdg-desktop-portal 1.18 to pick up settings from x-d-p-gtk (see flatpak/xdg-desktop-portal#1112) rather than a regression in x-d-p-gtk itself.

**Comment by lobroc** [comment]
Just fyi, this has been fixed in the most recent version of xdg-desktop-portal-kde (5.27.8-3)
