### ISSUE TITLE
Put focus on select

### ISSUE THREAD

**Issue by nedrichards** [flatpak/xdg-desktop-portal-gtk#45]
When launching the OpenURI portal from a flatpak app (in this case, Corebird) the focus is on the top line of the list, rather than on the item that appears to be 'preselected'. As such pressing Enter moves the focus to the top of the list (in this case Chrome) rather than opening the link in Chromium as expected.

![screenshot from 2017-01-25 14-28-28](https://cloud.githubusercontent.com/assets/302677/22294327/c9bb7d4a-e30a-11e6-8f58-8418f8e5f96c.png)

**Comment by matthiasclasen** [comment]
I think the new app chooser that we've just merged addresses this

**Comment by nedrichards** [comment]
It does!
