### ISSUE TITLE
Optional portals are broken with the Meson build

### ISSUE THREAD

**Issue by Sporif** [flatpak/xdg-desktop-portal-gtk#453]
I'm using Arch Linux and the optional portals don't work with v1.15.0.

qdbusviewer screenshots:

[Meson (v1.14.1+r30+g5fd3090)](https://i.imgur.com/J5TF4op.png)

[Autotools (v1.14.1+r29+g8e94605)](https://i.imgur.com/hhdklwY.png)

I tried rebuilding it with the settings portal explicitly enabled in the meson options but that made no difference.

There's also no output when running `/usr/lib/xdg-desktop-portal-gtk --verbose` with the meson build.

**Comment by ebassi** [comment]
What does "optional portals" mean? What optional portals?

What does "don't work" mean?

How did you build xdg-desktop-portal-gtk?

What kind of configuration options did you use?

Is there a build log?

**Comment by ebassi** [comment]
Released 1.15.1 with the fix. Thanks again for the report.
