### ISSUE TITLE
GTK4: Respect dark-theme variants (xsettings)

### ISSUE THREAD

**Issue by Stebalien** [flatpak/xdg-desktop-portal-gtk#464]
It's currently impossible to tell GTK4 flatpak apps to use a dark theme using the XSETTINGS protocol.

- Outside of flatpak, setting `Net/ThemeName` (xsettings) to `Adwaita-dark` will configure gtk4 applications to use a dark theme as long as `org.gnome.desktop.interface.color-scheme` is set to `default`.
- Inside flatpak, only `gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark` will switch to the dark theme.
- Inside flatpak, setting `Net/IconThemeName` works just fine.
- It appears that setting `Gtk/ColorScheme` (xsettings) to `prefer-dark` _should_ be the equivalent of `org.gnome.desktop.interface.color-scheme`, but it doesn't actually work anywhere (possibly a GTK bug?).

Unfortunately, while calling `gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"` technically "works", it's annoying to automate in a desktop environment (and shouldn't be necessary).

**Comment by Stebalien** [comment]
Nevermind, this is definitely a GTK4 bug. I was testing with gtk4-demo outside of flatpak (works) and d-spy/flatseal inside flatpak (doesn't work). But d-spy doesn't obey xsettings outside of flatpak either.

**Comment by ebassi** [comment]
GTK4 *by itself* does not support changing the color scheme: you need libadwaita for that, and libadwaita only supports the portal API, not XSETTINGS.

Also: the `Gtk/ColorScheme` setting is not used for the prefer dark/light color preference: it's a GTK2 relic for palettes of named colors.

**Comment by Stebalien** [comment]
> GTK4 by itself does not support changing the color scheme: you need libadwaita for that, and
> libadwaita only supports the portal API, not XSETTINGS.

Well, all I can say is that:

1. gtk4-demos respect xsettings for themes (although libadwaita-demos doesn't).
2. All gtk4 apps seem to respect xsettings for things like fonts and window decorations (close buttons, etc.).

> Also: the Gtk/ColorScheme setting is not used for the prefer dark/light color preference: it's a
> GTK2 relic for palettes of named colors.

Ah, I thought that was Gtk/ColorPalette.

**Comment by ebassi** [comment]
> 1. gtk4-demos respect xsettings for themes (although libadwaita-demos doesn't).

Yes, but the dark/light style preference is **not** a theme. The style preference is implemented by a theme itself, it doesn't switch the theme.

Libadwaita includes its own theme, to ensure consistency; this means it won't apply a system theme.

> All gtk4 apps seem to respect xsettings for things like fonts and window decorations (close buttons, etc.).

There is no XSETTINGS key for the style preference.

**Comment by Stebalien** [comment]
>  1 gtk4-demos respect xsettings for themes (although libadwaita-demos doesn't).
>
> Yes, but the dark/light style preference is not a theme. The style preference is implemented by
> a theme itself, it doesn't switch the theme.

Well, all I know is that switching the theme's name from Adwaita to Adwaita-dark changes from light-mode to dark mode (but only for the gtk4 demos and for gtk3 apps).

**Comment by ebassi** [comment]
This is an issue tracker, not a discussion forum, so at some point we'll have to stop this.

> Well, all I know is that switching the theme's name from Adwaita to Adwaita-dark changes from light-mode to dark mode (but only for the gtk4 demos and for gtk3 apps).

That's just a side effect of how GTK works; you're selecting a whole theme, not applying the style preference.

**Comment by Stebalien** [comment]
> This is an issue tracker, not a discussion forum, so at some point we'll have to stop this.

Yeah, thanks for all your help. I'll look at the implementing the portal
API and see how far I get.
