### ISSUE TITLE
Missing WM icon for top level windows

### ISSUE THREAD

**Issue by mariospr** [flatpak/xdg-desktop-portal-gtk#47]
At the moment there's not associated icon that the window manager can use when showing top level windows associated to the xdg-desktop-portal-gtk process. For instance, this is how it looks on Endless right now (although is way more visible when doing Alt-Tab, of course):

![missingicon](https://cloud.githubusercontent.com/assets/2197259/22556536/65bd80e4-e95f-11e6-9b5c-3cd4a10629c5.png)

It would be nice to have a different icon than that, if possible, as that one seem makes it look like broken.

**Comment by mariospr** [comment]
It might be interesting to change the visual name too, to something other than `xdg-desktop-portal-gtk`

**Comment by matthiasclasen** [comment]
https://github.com/flatpak/xdg-desktop-portal-gtk/pull/61 should address this. Can you test it ?

**Comment by mariospr** [comment]
It does, thanks!. I needed to modify it a bit to get it working on endless, though, see my comment in the PR
