### ISSUE TITLE
A way to configure OpenURI.

### ISSUE THREAD

**Issue by amano-kenji** [flatpak/xdg-desktop-portal-gtk#477]
I don't know how to configure xdg-desktop-portal-gtk to open a link with a specific program.

It doesn't use xdg-open. I'm confused.

**Comment by ebassi** [comment]
Yes, you are indeed confused: this is the issue tracker for the GTK implementation of the xdg-desktop-portal interfaces.

If you have questions about how to use the portals API, feel free to open a topic on [the xdg-desktop-portal discussions](https://github.com/flatpak/xdg-desktop-portal/discussions).

If you are using a toolkit, it's likely you already have portal-aware API.

**Comment by smcv** [comment]
> I don't know how to configure xdg-desktop-portal-gtk to open a link with a specific program.

I think the answer you are looking for is the MIME Apps Specification: https://specifications.freedesktop.org/mime-apps-spec/latest/

> It doesn't use xdg-open.

Correct. It uses code from GLib/GTK that implements the freedesktop.org MIME Apps Specification, linked above.

The xdg-open(1) tool has various desktop-environment-specific code paths, some of which use the MIME Apps Specification and some of which use legacy desktop-specific mechanisms.

**Comment by smcv** [comment]
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/using_the_desktop_environment_in_rhel_8/configuring-file-associations_using-the-desktop-environment-in-rhel-8#overriding-default-registered-application-for-individual-users_configuring-file-associations is a more tutorial-style description (written for RHEL 8, but it should be equally valid for any fd.o-based distribution).
