### ISSUE TITLE
Huge icon in open URI dialog

### ISSUE THREAD

**Issue by allanday** [flatpak/xdg-desktop-portal-gtk#49]
Whenever I try to open a link from a Flatpak, the "open with" dialog shows Firefox developer edition with a huge icon.

Screenshot: https://bug777868.bugzilla-attachments.gnome.org/attachment.cgi?id=344453

Originally reported here: https://bugzilla.gnome.org/show_bug.cgi?id=777868

**Comment by AsciiWolf** [comment]
I think this issue was [fixed](https://github.com/flatpak/xdg-desktop-portal-gtk/commit/4ddbabbb1e12a473bb23ac1d76064f2658c5274f).
