### ISSUE TITLE
Open URI dialog window handling

### ISSUE THREAD

**Issue by allanday** [flatpak/xdg-desktop-portal-gtk#56]
I regularly observe the following when opening links with Revolt:

 * The dialog is hidden behind the app window when it opens (you get an "is ready" notification for it, which although is technically wrong, does allow you to raise the window)
 * When you do raise the dialog window, it is located in the top-left corner of the display
 * The dialog window isn't modal to the app that called it
 * When the dialog is focused, the app menu reads "Xdg-desktop-portal-gtk" and has a missing icon

**Comment by jscurtu** [comment]
You should use gtk_show_uri_on_window (Gtk 3.22)

**Comment by allanday** [comment]
> You should use gtk_show_uri_on_window (Gtk 3.22)

I'm not the Revolt developer... are all of these issues a result of that, or only some?

**Comment by jscurtu** [comment]
All ..

**Comment by allanday** [comment]
Thanks, I've created an issue against Revolt for this: https://github.com/aperezdc/revolt/issues/49
