### ISSUE TITLE
URI dialog design improvements

### ISSUE THREAD

**Issue by allanday** [flatpak/xdg-desktop-portal-gtk#57]
Screenshot of the current dialog:

![screenshot from 2017-03-17 14-35-31](https://cloud.githubusercontent.com/assets/213068/24050530/fd8ba46c-0b26-11e7-8849-44eeb3982572.png)

There are various issues with this:

 * The whole thing feels rather tiny and cramped, particularly the header bar
 * It offers search when there are only two apps, and never likely to be many
 * Since this is a dialog that you might face a lot, the two clicks (one to choose an app and the other to select) seems a bit much. I'd maybe just go for one.

A mockup for how it could be made to look a bit better:

![alt text](https://raw.githubusercontent.com/gnome-design-team/gnome-mockups/master/portals/open-uri.png "mockup")

**Comment by matthiasclasen** [comment]
thanks, that does look nicer
