### ISSUE TITLE
.desktop Exec line not generated correctly

### ISSUE THREAD

**Issue by jbicha** [flatpak/xdg-desktop-portal-gtk#66]
The xdg-desktop-portal-gtk 0.6 tarball has this line in `data/xdg-desktop-portal-gtk.desktop`

`Exec=/home/mclasen/gnome/libexec/xdg-desktop-portal-gtk`

**Comment by jbicha** [comment]
Maybe your libexec is being set by jhbuild?

A few more things I saw.

The broken xdg-desktop-portal-gtk.desktop is in the root directory of the tarball not in data/

Line 19 is different than line 5 in
https://github.com/flatpak/xdg-desktop-portal-gtk/blob/master/data/Makefile.am.inc

**Comment by matthiasclasen** [comment]
https://github.com/flatpak/xdg-desktop-portal-gtk/pull/67 should fix this

**Comment by jbicha** [comment]
Yes, #67 fixes my issue, at least with autoreconf.

**Comment by mariospr** [comment]
Oops! I missed the `dist_`prefix during the previous review, sorry about that. Checking the PR now...
