### ISSUE TITLE
Unable to init server: Could not connect: Connection refused

### ISSUE THREAD

**Issue by dumblob** [flatpak/xdg-desktop-portal-gtk#72]
After a minor update of my Arch Linux system (flatpak 0.8.3 -> 0.9.1, some Gnome packages, etc.) I noticed Gnome applications (e.g. Evince) start extremely slowly while the system load is zero. I found the issue described on https://bbs.archlinux.org/viewtopic.php?id=224787 . To me it seems systemd sees flatpak service as dependency and runs it, but it fails and by default systemd probably waits several tens of seconds if the service will not recover.

On the internet I didn't find absolutely anything suspicious, but to me it seems `xdg-desktop-portal-gtk` gets the `DISPLAY` environment variable somehow incorrectly (on my notebook: `DISPLAY=:1`).

Could you please comment on this somehow? I don't have sufficient knowledge and currently unfortunately not enough time to study the source code.

**Comment by matthiasclasen** [comment]
xdg-desktop-portal and xdg-desktop-portal-gtk are d-bus activated session services like any other. 

You'll have to make sure that your session setup arranges for DISPLAY to be set in the activation environment of the session bus.

**Comment by dumblob** [comment]
Thank you @matthiasclasen for the pointers. Thanks to them I found out, that running `dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY` does exactly missing propagation (note the `--systemd` argument, without which the applications still start with the huge delay).
