### ISSUE TITLE
xdg-desktop-portal-gtk doesnt restart after I kill it

### ISSUE THREAD

**Issue by ocrete** [flatpak/xdg-desktop-portal-gtk#89]
I was trying the Builder nightly through Flatpak, and when I tried to save a file, I got into a condition where the file save dialog just wouldn't respond. So I killed it.. and now it doesn't restart itself and builder just can't save new files.

This is using xdg-desktop-portal-gtk-0.7-1.fc26.x86_64

**Comment by matthiasclasen** [comment]
The portal should get dbus-activated, i believe. Does it start working again if you kill the frontend process (xdg-desktop-portal) too ?

**Comment by ocrete** [comment]
Now it seems to work , no idea what changed... I'll re-open if I ever manage to reproduce.
