### ISSUE TITLE
Empty application chooser

### ISSUE THREAD

**Issue by bochecha** [flatpak/xdg-desktop-portal-gtk#90]
Yesterday @hadess send this link on IRC: ftp://ftp.vim.org/pub/vim/patches/8.0/8.0.0679

Now he does have weird ways to pass the time, but I'm not going to judge... especially since I actually tried to click that link.

I was rewarded with the following:

![screenshot from 2017-08-11 11-48-54](https://user-images.githubusercontent.com/272170/29208647-382f5a82-7e8b-11e7-81a7-b40937e6ea23.png)

There probably should be a message about how no installed application seem to handle the request.

**Comment by matthiasclasen** [comment]
I believe this is fixed

![screenshot from 2018-06-21 14-43-17](https://user-images.githubusercontent.com/4834845/41738922-79a5b970-7561-11e8-86f9-f3ec5205b83d.png)
